In [1]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivatives_sigmoid(x):
    return (x)*(1-(x))


X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([1,1,0]).T
learning_rate = 0.1
epochs = 1

wh = np.random.random([4,3])
bh = np.random.random([1,3])
wout = np.random.random([3,1])
bout = np.random.random([1,1])
print('Weights at hidden layer')
print(wh)
print('Biases at hidden layer')
print(bh)
print('Weights at output layer')
print(wout)
print('Biases at output layer')
print(bout)

hidden_layer_input = np.dot(X,wh) + bh
hiddenlayer_activations = sigmoid(hidden_layer_input)


output_layer_input = np.dot(hiddenlayer_activations,wout ) + bout
output = sigmoid(output_layer_input)
output = np.ndarray.flatten(output) # reshaping output
E = np.array(y-output)

slope_output_layer= derivatives_sigmoid(output)
d_output = E * slope_output_layer
d_output = np.reshape(d_output,[3,1]) # reshaping d_output

Error_at_hidden_layer = np.dot(d_output, wout.T)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

wout = wout + np.dot(hiddenlayer_activations.T,d_output) * learning_rate
bout = bout + np.sum(d_output, axis=0)*learning_rate
wh = wh+ np.dot(X.T,d_hiddenlayer) * learning_rate
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate

print('Updated weights at hidden layer')
print(wh)
print('Updated biases at hidden layer')
print(bh)
print('Updated weights at output layer')
print(wout)
print('Updated biases at output layer')
print(bout)


Weights at hidden layer
[[0.28053676 0.79009083 0.07621028]
 [0.59237517 0.06704501 0.46988839]
 [0.61531922 0.55904024 0.88846681]
 [0.26862854 0.20229756 0.50748303]]
Biases at hidden layer
[[0.76540894 0.89194138 0.26654593]]
Weights at output layer
[[0.84512836]
 [0.49272133]
 [0.97383867]]
Biases at output layer
[[0.33257888]]
Updated weights at hidden layer
[[0.28069577 0.7901515  0.07643766]
 [0.59141716 0.06630644 0.46849211]
 [0.61547824 0.55910091 0.88869419]
 [0.26773502 0.20158397 0.50617211]]
Updated biases at hidden layer
[[0.76460993 0.89126348 0.26537704]]
Updated weights at output layer
[[0.83953268]
 [0.48782265]
 [0.9686626 ]]
Updated biases at output layer
[[0.3258472]]
